// Web-console or Public APIs
const apiUrls = {
    AU_001: '/v1/api/discovery/account/master',
    AU_002: '/v1/api/cloud/account',
    AU_003: '/v2/api/resources/global/clouds',
    AU_004: '/v1/api/discovery/account/member',
    AU_005: '/v1/api/tool/jira/login/token',
    AU_006: '/v1/api/tool/jira/deletetoken',
    AU_007: '/v2/api/resources/global/jira',
    AU_008: '/v1/api/jira/projects',
    AU_009: '/v1/api/tool/jira/create',
    AU_010: '/v1/api/jira/issue-types',
    AU_011: '/v1/api/jira/users',
    AU_012: '/v1/api/jira/issue-fields',
    AU_013: '/v1/api/jira/settings',
    AU_014: '/v2/api/resources/global/dashboard/jira/priority/counts',
    AU_015: '/v2/api/resources/global/dashboard/pr/status/counts',
    AU_016: '/v2/api/resources/global/pr',
    AU_017: '/v1/api/policy',
    AU_018: '/v1/api',
    AU_019: 'v1/api/rule/test',
    AU_020: '/v1/api/rule',
    AU_021: '/v1/api/rego',
    AU_022: '/v1/api/rego/save',
    AU_023: '/v1/api/rego/resources',
    AU_024: '/v1/api/rego/benchmarks',
    AU_025: '/v1/api/rego/categories',
    AU_026: '/v1/api/rego/severities',
    AU_027: '/v1/api/rego/test',
    AU_028: '/v2/api/resources/global/rule-violations',
    AU_030: '',
    AU_031: '/v2/api/resources/global/pipeline/summary',
    AU_032: '/v1/api/bot-config',
    AU_034: '/v1/api/code',
    AU_035: '/v1/api/repo',
    AU_036: '/v2/api/resources/global/repos',
    AU_037: '/v2/api/resources/global/clusters',
    AU_038: '/v1/api/jira/priorities',
    AU_039: '/v2/api/resources/global/resources',
    AU_040: '/v2/api/resources/global/category/compliance',
    AU_041: '/v2/api/resources/global/types',
    AU_042: '/v2/api/resources/global/violations',
    AU_043: '/v2/api/resources/global/trends/insights/count',
    AU_044: '/v2/api/resources/global/trends/basic/count',
    AU_045: '/v2/api/resources/global/filters',
    AU_046: '/v2/api/resources/global/pipeline/runs',
    AU_047: '/v1/api/env',
    AU_048: '/v2/api/resources/global/metering/types/count',
    AU_049: '',
    AU_050: '/v2/api/resources/global/dashboard/failing/policies/severity',
    AU_051: '/v1/api/rtm/events/filters',
    AU_052: '/v2/api/resources/global/projects',
    AU_053: '/v1/api/repoonboard',
    AU_054: '/v1/api/rtm/events/count',
    AU_055: '/v2/api/resources/global/counts',
    AU_056: '/v2/api/resources/global/dashboard/failing/policies/top',
    AU_057: '/v2/api/resources/global/dashboard/failing/types/top',
    AU_058: '/v1/api/code/integration/status',
    AU_059: '/v1/api/iacscan/env/status',
    AU_060: '/v1/api/cloudscan/env/status',
    AU_061: '/v1/api/discovery/account/credential/validate',
    AU_062: '/v1/api/cloud/aws/vpcs',
    AU_063: '/v1/api/cloud/azure/env/0/resource/managementgroups',
    AU_064: '/v1/api/cloud/azure/env/0/resource/subscriptions',
    AU_065: '/v1/api/cloud/azure/resourcegroups',
    AU_066: '/v2/api/resources',
    AU_067: '/v1/api/cloudscan',
    AU_068: '/v1/api/cloudscan/env',
    AU_069: '/v2/api/resources/violations/ignore',
    AU_070: '/v2/api/resources',
    AU_071: '/v2/api/resources/global/vulnerabilities/count',
    AU_072: '/v1/api/cloudscan/groupscan',
    AU_073: '/v2/api/resources/global/asset/vulnerabilities/vpr/count',
    AU_074: '/v2/api/resources/global/asset/vulnerabilities/count',
    AU_075: '/v1/api/rego/resource/aws_instance/config',
    AU_076: '/v1/api/alert-configuration/runtime',
    AU_077: '/v2/api/resources/global/rule-violations/filters',
    AU_078: '/v2/api/resources/global/compliance/graph',
    AU_079: '/v2/api/resources/global/policy/compliance',
    AU_080: '/v2/api/resources/global/rule-count/compliance/chart',
    AU_081: '/api/v1/environments',
    AU_082: '/api/v1/resources',
    AU_083: '/api/v1/drifts',
    AU_084: '/api/v1/metrics',
    AU_085: '/api/v1/violations',
    AU_086: '/api/v1/projects',
    AU_087: '/api/v1/repos',
    AU_088: '/api/v1/scans',
    AU_089: '/api/v1/pr',
    AU_090: '/api/v1/exceptions',
    AU_091: '/external/api',
    AU_092: '/v1/api/user',
    AU_093: '/v1/api/invitecodeadmin/scm',
    AU_094: '/v1/api/invitecodeadmin/cloud',
    AU_095: '/v1/api/developerinvitestatus',
    AU_096: '/v1/api/onboardingstatus',
    AU_097: '/v2/api/resources/global/rule-count/compliance/chart',
    AU_098: '/v2/api/resources/global/compliance/filters',
    AU_101: '/v1/api/alert-configuration',
    AU_102: '/v1/api/application',
    AU_103: '/v1/api/bot-config',
    AU_104: '/v1/api/bot/status',
    AU_105: '/v1/api/code',
    AU_106: '/v1/api/application/helm/cli/kubescan',
    AU_107: '/v2/api/resources/import',
    AU_108: '/v1/api/reports',
    AU_109: '/v2/api/resources/global/policy/map/benchmark',
    AU_110: '/v2/api/resources/global/violations/count',
    AU_111: '/v2/api/resources/global/types/paginated',
    AU_112: '/v2/api/resources/global/metering/types/count',
    AU_113: '/v2/api/resources/global/history/summary',
    AU_114: '/v2/api/resources/global/dashboard',
    AU_115: '/v2/api/resources/global/counts/other',
    AU_116: '/v2/api/resources/global/burst',
    AU_117: '/api/v1/account/create',
    AU_118: '/api/v1/account/fetch',
    AU_119: '/api/v1/account/update',
    AU_120: '/api/v1/account/configure',
    AU_121: '/v1/api/discovery/association',
    AU_122: '/v2/api/resources/global/category/count',
    AU_123: '/v1/api/alerts/count',
    AU_124: '/v1/api/rtm/events',
    AU_125: '/v1/api/code/github/repos',
    AU_126: '/v1/api/code/bitbucket/repos',
    AU_127: '/v1/api/code/gitlab/repos',
    AU_128: '/v1/api/code/microsoft/repos',
    AU_129: '/v1/api/code/awscodecommit/repos',
    AU_131: '/v2/api/resources/global/asset/vulnerabilities/accessible/count',
    AU_132: '/v1/api/discovery/account/member/filters',
    AU_141: '/v2/api/resources/global/dashboard/containers/kubernetes/count',
    AU_142: '/v2/api/resources/global/dashboard/containers/kubernetes/severity',
    AU_143: '/v1/api/chasm/insight',
    AU_144: '/v1/api/chasm/insight-setting',

  };

// Non web-console, Non public but, external and thirdparty
const nonApiUrls = {
    NAU_001: 'https://www.orgName.com/downloads/api/v2/pages/cloud-security/files',
    NAU_003: 'https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacksets/create',
    NAU_004: 'https://downloads.accurics.com/downloads/io/create_tcs_aws_readonly_role.sh',
    NAU_005: 'https://s3.us-east-1.amazonaws.com/orgName-connectors/cloud-templates/aws/us-2b/orgNamecs-role-aws-read-only-cft.yml',
    NAU_006: '/unzip/helm/helm/cli-kubescan/data/k8s-runtime-config-file.json',
    NAU_007: 'https://bitbucket.org/tenb-qa/acqa-repo1-aws-tf12-part1.git',
    NAU_008: 'https://bitbucket.org/tenb-qa/acqa-repo1-aws-tf12-part2.git',
    NAU_009: 'https://bitbucket.org/tenb-qa/acqa-repo8-gcp-tf13.git',
    NAU_010: 'https://bitbucket.org/tenb-qa/acqa-repo9-azure-tf12.git',
    NAU_011: 'https://bitbucket.org/tenb-qa/acqa-repo6-aws-cft.git',
    NAU_012: 'https://github.com/tenb-qa/acqa-repo16-aws-ignoreUnignore-tester.git',
    NAU_013: 'https://bitbucket.org/tenb-qa/acqa-tfc-remote-private-module-authentication.git',
    NAU_014: Cypress.config('baseUrl').replace("/apiHandle", "")+'/api/v3/findings/vulnerabilities/host/analysis',
    NAU_015: Cypress.config('baseUrl').replace("/apiHandle", "")+'/api/v3/assets/search',
    NAU_016: 'https://github.com/tenb-qa/performance-test-resources.git'

}


function getUrlByName(urlName) {
  // In case of non web-console URLs
  if(urlName.indexOf('NAU_') > -1){
    return (nonApiUrls[urlName] || null);
  }
  // In case of tcs APIs
  else {
    return Cypress.config('baseUrl') + (apiUrls[urlName] || null);
  }
}

export { getUrlByName };